receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:8080
            - http://localhost:8090
            - http://*
            
  zipkin:

exporters:
  logging:
    loglevel: debug
  otlp:
   endpoint: tempo-eu-west-0.grafana.net:443
   headers:
     authorization: Basic 

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [zipkin, otlp]
      processors: [batch]
      exporters: [logging, otlp]